# Generated by Django 5.2.8 on 2025-11-22 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clientReg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientName', models.CharField(max_length=100)),
                ('clientEmail', models.EmailField(default='client@gmail.com', max_length=254, unique=True)),
                ('clientPhone', models.CharField(max_length=10)),
                ('clientLocation', models.CharField(default='yourcity', max_length=50)),
                ('clientPhoto', models.CharField(max_length=500)),
                ('userPassword', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='userReg',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=50)),
                ('userEmail', models.EmailField(max_length=254, unique=True)),
                ('userPhone', models.CharField(max_length=10, unique=True)),
                ('userLocation', models.CharField(default='yourcity', max_length=100)),
                ('userPassword', models.CharField(max_length=255)),
            ],
        ),
    ]
