# Generated by Django 5.1.5 on 2025-11-23 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientreg',
            name='userPassword',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
