# Generated by Django 5.1.5 on 2025-11-23 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users_app', '0002_alter_clientreg_userpassword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientreg',
            name='userPassword',
        ),
        migrations.RemoveField(
            model_name='userreg',
            name='userEmail',
        ),
        migrations.RemoveField(
            model_name='userreg',
            name='userPassword',
        ),
        migrations.AddField(
            model_name='clientreg',
            name='clientPassword',
            field=models.CharField(default='password123', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userreg',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userreg',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='userreg',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userreg',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userreg',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='userreg',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='userreg',
            name='password',
            field=models.CharField(default='example@example.com', max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userreg',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
