# Generated by Django 5.1.5 on 2025-11-23 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0003_remove_clientreg_userpassword_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userreg',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='userreg',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='userreg',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='clientreg',
            name='clientEmail',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
