# Generated by Django 5.2.7 on 2025-11-25 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0005_userreg_groups_userreg_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientreg',
            name='clientPhone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userreg',
            name='userPhone',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
