# Generated by Django 5.1.5 on 2025-11-27 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0007_alter_clientreg_clientphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientreg',
            name='clientPhoto',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
