# Generated by Django 5.1.5 on 2025-11-28 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0008_alter_clientreg_clientphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientreg',
            name='clientPhoto',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
